create table countries (
	id INT,
	title VARCHAR(50),
	iso VARCHAR(50)
);
insert into countries (id, title, iso) values (1, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (2, 'China', 'CN');
insert into countries (id, title, iso) values (3, 'Guatemala', 'GT');
insert into countries (id, title, iso) values (4, 'Nicaragua', 'NI');
insert into countries (id, title, iso) values (5, 'Ireland', 'IE');
insert into countries (id, title, iso) values (6, 'Argentina', 'AR');
insert into countries (id, title, iso) values (7, 'China', 'CN');
insert into countries (id, title, iso) values (8, 'China', 'CN');
insert into countries (id, title, iso) values (9, 'Philippines', 'PH');
insert into countries (id, title, iso) values (10, 'Brazil', 'BR');
insert into countries (id, title, iso) values (11, 'Japan', 'JP');
insert into countries (id, title, iso) values (12, 'China', 'CN');
insert into countries (id, title, iso) values (13, 'Russia', 'RU');
insert into countries (id, title, iso) values (14, 'Madagascar', 'MG');
insert into countries (id, title, iso) values (15, 'Philippines', 'PH');
insert into countries (id, title, iso) values (16, 'Niger', 'NE');
insert into countries (id, title, iso) values (17, 'Japan', 'JP');
insert into countries (id, title, iso) values (18, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (19, 'Thailand', 'TH');
insert into countries (id, title, iso) values (20, 'Philippines', 'PH');
insert into countries (id, title, iso) values (21, 'Brazil', 'BR');
insert into countries (id, title, iso) values (22, 'France', 'FR');
insert into countries (id, title, iso) values (23, 'Poland', 'PL');
insert into countries (id, title, iso) values (24, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (25, 'Jamaica', 'JM');
insert into countries (id, title, iso) values (26, 'Japan', 'JP');
insert into countries (id, title, iso) values (27, 'Portugal', 'PT');
insert into countries (id, title, iso) values (28, 'Russia', 'RU');
insert into countries (id, title, iso) values (29, 'Uruguay', 'UY');
insert into countries (id, title, iso) values (30, 'Tanzania', 'TZ');
insert into countries (id, title, iso) values (31, 'Portugal', 'PT');
insert into countries (id, title, iso) values (32, 'Finland', 'FI');
insert into countries (id, title, iso) values (33, 'Japan', 'JP');
insert into countries (id, title, iso) values (34, 'Philippines', 'PH');
insert into countries (id, title, iso) values (35, 'Kyrgyzstan', 'KG');
insert into countries (id, title, iso) values (36, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (37, 'Russia', 'RU');
insert into countries (id, title, iso) values (38, 'Zambia', 'ZM');
insert into countries (id, title, iso) values (39, 'Costa Rica', 'CR');
insert into countries (id, title, iso) values (40, 'Brazil', 'BR');
insert into countries (id, title, iso) values (41, 'Canada', 'CA');
insert into countries (id, title, iso) values (42, 'Czech Republic', 'CZ');
insert into countries (id, title, iso) values (43, 'Czech Republic', 'CZ');
insert into countries (id, title, iso) values (44, 'China', 'CN');
insert into countries (id, title, iso) values (45, 'Peru', 'PE');
insert into countries (id, title, iso) values (46, 'China', 'CN');
insert into countries (id, title, iso) values (47, 'Burkina Faso', 'BF');
insert into countries (id, title, iso) values (48, 'Philippines', 'PH');
insert into countries (id, title, iso) values (49, 'China', 'CN');
insert into countries (id, title, iso) values (50, 'Spain', 'ES');
insert into countries (id, title, iso) values (51, 'China', 'CN');
insert into countries (id, title, iso) values (52, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (53, 'Argentina', 'AR');
insert into countries (id, title, iso) values (54, 'Sweden', 'SE');
insert into countries (id, title, iso) values (55, 'France', 'FR');
insert into countries (id, title, iso) values (56, 'Japan', 'JP');
insert into countries (id, title, iso) values (57, 'Russia', 'RU');
insert into countries (id, title, iso) values (58, 'Canada', 'CA');
insert into countries (id, title, iso) values (59, 'Czech Republic', 'CZ');
insert into countries (id, title, iso) values (60, 'China', 'CN');
insert into countries (id, title, iso) values (61, 'Chad', 'TD');
insert into countries (id, title, iso) values (62, 'Mongolia', 'MN');
insert into countries (id, title, iso) values (63, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (64, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (65, 'Cameroon', 'CM');
insert into countries (id, title, iso) values (66, 'Croatia', 'HR');
insert into countries (id, title, iso) values (67, 'Norway', 'NO');
insert into countries (id, title, iso) values (68, 'China', 'CN');
insert into countries (id, title, iso) values (69, 'Philippines', 'PH');
insert into countries (id, title, iso) values (70, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (71, 'Philippines', 'PH');
insert into countries (id, title, iso) values (72, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (73, 'China', 'CN');
insert into countries (id, title, iso) values (74, 'Argentina', 'AR');
insert into countries (id, title, iso) values (75, 'Russia', 'RU');
insert into countries (id, title, iso) values (76, 'Czech Republic', 'CZ');
insert into countries (id, title, iso) values (77, 'China', 'CN');
insert into countries (id, title, iso) values (78, 'Mexico', 'MX');
insert into countries (id, title, iso) values (79, 'China', 'CN');
insert into countries (id, title, iso) values (80, 'China', 'CN');
insert into countries (id, title, iso) values (81, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (82, 'Sweden', 'SE');
insert into countries (id, title, iso) values (83, 'Poland', 'PL');
insert into countries (id, title, iso) values (84, 'Russia', 'RU');
insert into countries (id, title, iso) values (85, 'China', 'CN');
insert into countries (id, title, iso) values (86, 'Jordan', 'JO');
insert into countries (id, title, iso) values (87, 'China', 'CN');
insert into countries (id, title, iso) values (88, 'Indonesia', 'ID');
insert into countries (id, title, iso) values (89, 'Thailand', 'TH');
insert into countries (id, title, iso) values (90, 'Nepal', 'NP');
insert into countries (id, title, iso) values (91, 'Philippines', 'PH');
insert into countries (id, title, iso) values (92, 'China', 'CN');
insert into countries (id, title, iso) values (93, 'Saint Vincent and the Grenadines', 'VC');
insert into countries (id, title, iso) values (94, 'Sweden', 'SE');
insert into countries (id, title, iso) values (95, 'Russia', 'RU');
insert into countries (id, title, iso) values (96, 'Peru', 'PE');
insert into countries (id, title, iso) values (97, 'China', 'CN');
insert into countries (id, title, iso) values (98, 'Czech Republic', 'CZ');
insert into countries (id, title, iso) values (99, 'Poland', 'PL');
insert into countries (id, title, iso) values (100, 'Croatia', 'HR');
